name: Build

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - ESPectrum
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pyserial>=3.0
          pip install pyelftools>=0.22
          pip install gdbgui>=0.13.2.0
          pip install pygdbmi<=0.9.0.2
          pip install python-socketio<5
          pip install jinja2<3.1
          pip install itsdangerous<2.1
          pip install reedsolo>=1.5.3,<=1.5.4
          pip install bitstring>=3.1.6,<4
          pip install ecdsa>=0.16.0
          pip install construct==2.10.54
          pip install python-socketio==4.6.1
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
      - name: Run PlatformIO
        run: |
          platformio run -e ${{ matrix.variant }}
